### ISSUE TITLE
Nuget package?

### ISSUE THREAD

**Issue by jamieyello** [LogosBible/bsdiff.net#13]
Hi, I'm planning on using this library in a data syncing framework ([in case you're curious](https://github.com/jamieyello/NoDb)). I can copy over the code and use it in the project, which would include a copy of this repo in my repo, but I would rather use a nuget package of this.

**Comment by bgrainger** [comment]
The NuGet package is linked from the main README: https://www.nuget.org/packages/BsDiff.
