### ISSUE TITLE
BsDiffPatchChunked

### ISSUE THREAD

**Issue by tenyo-tyankov** [LogosBible/bsdiff.net#7]
Hi
First, congratulations for this c# port of bsdiff algorithm. It is very helpful for me, so I decide to share some code :)
I decide to write a wrapper to avoid problem with memory consumption on large files. The wrapper uses yours BinaryPatchUtility.cs (with just one modification) as basis but splits files in chunks and make diffs over them, then combine all chunks in single patch file. Because of slow diff generation on large files (over 1Gb) wrapper has feature to make diffs on chunks in parallel mode. When applying patch, wrapper reads chunk diffs and make new file from them. 
Wrapper and demo source code.[BsDiffPatchChunked.zip](https://github.com/LogosBible/bsdiff.net/files/495641/BsDiffPatchChunked.zip)

Best,
	Tenyo Tyankov

**Comment by bgrainger** [comment]
Thanks for submitting your code! 

If you'd like any changes to be integrated into this code, please submit them as a pull request. (Although it sounds like you're mostly creating a new project and not adding to this one.)

Help on creating a PR can be found at:
* https://help.github.com/articles/creating-a-pull-request-from-a-fork/
* https://yangsu.github.io/pull-request-tutorial/
